#!/bin/sh

usage() {
	err "Invalid usage. Usage: "
	err "\t$0 init"
	err "\t$0 attach <json params>"
	err "\t$0 detach <mount device>"
	err "\t$0 mount <mount dir> <mount device> <json params>"
	err "\t$0 unmount <mount dir>"
	exit 1
}

err() {
	echo -ne $* 1>&2
}

log() {
	echo -ne $* >&1
}

ismounted() {
    echo "ismounted() called" >> /tmp/s3fs-container.log

	MOUNT=`findmnt -n ${MNTPATH} 2>/dev/null | cut -d' ' -f1`
	if [ "${MOUNT}" == "${MNTPATH}" ]; then
		echo "1"
	else
		echo "0"
	fi
}

attach() {
    echo "attach() called" >> /tmp/s3fs-container.log
    log "{\"status\": \"Success\"}"
	exit 0
}

detach() {
    echo "detach() called" >> /tmp/s3fs-container.log
	log "{\"status\": \"Success\"}"
	exit 0
}

domount() {
    echo "domount() called" >> /tmp/s3fs-container.log
	MNTPATH=$1

	FSTYPE=$(echo $2|jq -r '.["kubernetes.io/fsType"]')
	BUCKET=$(echo $2|jq -r '.["bucket"]')
	AWS_ACCESS_KEY_ID=$(echo $2|jq -r '.["AWS_ACCESS_KEY_ID"]')
	AWS_SECRET_ACCESS_KEY=$(echo $2|jq -r '.["AWS_SECRET_ACCESS_KEY"]')


  echo "domount() called aws_access_key_id: ${AWS_ACCESS_KEY_ID}" >> /tmp/s3fs-container.log
    echo "domount() called aws_secret_access_key: ${AWS_SECRET_ACCESS_KEY}" >> /tmp/s3fs-container.log
      echo "domount() called BUCKET: ${BUCKET}" >> /tmp/s3fs-container.log

	if [ $(ismounted) -eq 1 ] ; then
	    echo "domount() called, returning as its already mounted!  ${MNTPATH} " >> /tmp/s3fs-container.log
		log "{\"status\": \"Success\"}"
		exit 0
	fi

    mkdir -p ${MNTPATH} &> /dev/null

    DOCKER_OUT=`docker run -d --privileged -e S3User=${AWS_ACCESS_KEY_ID} -e S3Secret=${AWS_SECRET_ACCESS_KEY} -v ${MNTPATH}:/mnt/mountpoint:shared --cap-add SYS_ADMIN s3fs ${BUCKET} /mnt/mountpoint -o passwd_file=/etc/passwd-s3fs -d -d -f -o f2 -o curldbg`
    echo "domount() docker container output: ${DOCKER_OUT}" >> /tmp/s3fs-container.log
    log "{\"status\": \"Success\", \"docker-out\":\"${DOCKER_OUT}\"}"

	exit 0
}

unmount() {
        echo "unmount() called" >> /tmp/s3fs-container.log
	MNTPATH=$1
	if [ $(ismounted) -eq 0 ] ; then
                echo "unmount() called, but already unmounted " >> /tmp/s3fs-container.log
		log "{\"status\": \"Success\"}"
		exit 0
	fi

	umount ${MNTPATH} &> /dev/null
	if [ $? -ne 0 ]; then
		err "{ \"status\": \"Failed\", \"message\": \"Failed to unmount volume at ${MNTPATH}\"}"
		exit 1
	fi
	rmdir ${MNTPATH} &> /dev/null

	log "{\"status\": \"Success\"}"
	exit 0
}


echo "--------------------------------------------------------------`date`------------------------------------" >> /tmp/s3fs-container.log
echo $@ >> /tmp/s3fs-container.log

op=$1

if [ "$op" = "init" ]; then
	log "{\"status\": \"Success\"}"
	exit 0
fi

if [ $# -lt 2 ]; then
	usage
fi

shift

case "$op" in
	attach)
		attach $*
		;;
	detach)
		detach $*
		;;
	mount)
		domount $*
		;;
	unmount)
		unmount $*
		;;
	*)
		usage
esac

exit 1

