#!/bin/sh

usage() {
	err "Invalid usage. Usage: "
	err "\t$0 init"
	err "\t$0 attach <json params>"
	err "\t$0 detach <mount device>"
	err "\t$0 mount <mount dir> <mount device> <json params>"
	err "\t$0 unmount <mount dir>"
	exit 1
}

err() {
	echo -ne $* 1>&2
}

log() {
	echo -ne $* >&1
}

ismounted() {
    echo "ismounted() called" >> /tmp/s3fs-container.log

	MOUNT=`findmnt -n ${MNTPATH} 2>/dev/null | cut -d' ' -f1`
	if [ "${MOUNT}" == "${MNTPATH}" ]; then
		echo "1"
	else
		echo "0"
	fi
}

attach() {
    echo "attach() called" >> /tmp/s3fs-container.log
    log "{\"status\": \"Success\"}"
	exit 0
}

detach() {
    echo "detach() called" >> /tmp/s3fs-container.log
	log "{\"status\": \"Success\"}"
	exit 0
}

domount() {
    echo "domount() called" >> /tmp/s3fs-container.log
	MNTPATH=$1

	FSTYPE=$(echo $2|jq -r '.["kubernetes.io/fsType"]')
	BUCKET=$(echo $2|jq -r '.["bucket"]')
	S3User=$(echo $2|jq -r '.["S3User"]')
	S3Secret=$(echo $2|jq -r '.["S3Secret"]')

	if [ $(ismounted) -eq 1 ] ; then
		log "{\"status\": \"Success\"}"
		exit 0
	fi

    mkdir -p ${MNTPATH} &> /dev/null

    docker run --privileged -e S3User=$S3User -e S3Secret=$S3Secret -v ${MNTPATH}:/mnt/mountpoint:shared --cap-add SYS_ADMIN s3fs ${BUCKET} /mnt/mountpoint -o passwd_file=/etc/passwd-s3fs -d -d -f -o f2 -o curldbg

    log "{\"status\": \"Success\"}"

	exit 0
}

unmount() {
    echo "unmount() called" >> /tmp/s3fs-container.log
	MNTPATH=$1
	if [ $(ismounted) -eq 0 ] ; then
		log "{\"status\": \"Success\"}"
		exit 0
	fi

	umount ${MNTPATH} &> /dev/null
	if [ $? -ne 0 ]; then
		err "{ \"status\": \"Failed\", \"message\": \"Failed to unmount volume at ${MNTPATH}\"}"
		exit 1
	fi
	rmdir ${MNTPATH} &> /dev/null

	log "{\"status\": \"Success\"}"
	exit 0
}


echo "--------------------------------------------------------------`date`------------------------------------" >> /tmp/s3fs-container.log
echo $@ >> /tmp/s3fs-container.log

op=$1

if [ "$op" = "init" ]; then
	log "{\"status\": \"Success\"}"
	exit 0
fi

if [ $# -lt 2 ]; then
	usage
fi

shift

case "$op" in
	attach)
		attach $*
		;;
	detach)
		detach $*
		;;
	mount)
		domount $*
		;;
	unmount)
		unmount $*
		;;
	*)
		usage
esac

exit 1

